/**
 * Linha dos Ecos — o mapa é desenhado em tiles no canvas: chão, árvores, criaturas e heróis são entidades 2D reais.
 * Nenhuma imagem de cenário ou marcador geométrico participa do campo de jogo.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { classes, endings, primordialDragons, races, regions, type Stats } from "../game/content";
import type { CharacterProfile } from "./RpgGame";
import { CharacterPreview, profileStats } from "./RpgGame";

type EnemyKind = "wolf" | "boar" | "goblin";
type Enemy = { id: string; x: number; y: number; health: number; maxHealth: number; kind: EnemyKind; alive: boolean; hurt: number; phase: number };
type Essence = { id: string; x: number; y: number; phase: number };
type Player = { x: number; y: number; health: number; maxHealth: number; focus: number; maxFocus: number; level: number; xp: number; essence: number; facing: number; attack: number; special: number; invulnerable: number; evolved: boolean; potions: number };
type Npc = { id: string; name: string; role: string; x: number; y: number; race: "human" | "elf" | "goblin"; line: string; quest: string };
type Menu = "none" | "character" | "inventory" | "map" | "quests" | "village" | "codex" | "dungeon";
type Hud = { health: number; maxHealth: number; focus: number; maxFocus: number; level: number; xp: number; essence: number; potions: number; wolves: number; notice: string; quest: string; menu: Menu; buildings: string[]; wood: number; ore: number; food: number; gold: number };

const WORLD_W = 42;
const WORLD_H = 30;
const Npcs: Npc[] = [
  { id: "mira", name: "Mira de Musgo", role: "Guardião da vila", x: 28.5, y: 20.1, race: "human", line: "Os lobos foram tocados pela Ruptura. A vila não quer caçadores: quer alguém que entenda o Éter.", quest: "Expulse os Lobos Primordiais da trilha norte." },
  { id: "thalion", name: "Thalion", role: "Emissário élfico", x: 19.7, y: 8.4, race: "elf", line: "A Árvore Primordial ainda sonha. Não confunda silêncio com paz.", quest: "Escute os espíritos da raiz antiga." },
  { id: "nix", name: "Nix", role: "Mercador goblin", x: 31.4, y: 23.2, race: "goblin", line: "Eu vendo coisas honestas. As desonestas custam mais, mas são muito mais interessantes.", quest: "Troque recursos para fortalecer a Vila de Musgo." },
];

const dialogueChoices: Record<string, { label: string; effect: string; faction: string; amount: number }[]> = {
  mira: [{ label: "Defender a Vila de Musgo", effect: "A vila passa a confiar no seu eco.", faction: "Vila de Musgo", amount: 2 }, { label: "Perguntar pela Ordem da Vigília", effect: "Você descobre que a Ordem esconde informações sobre a Ruptura.", faction: "Ordem da Vigília", amount: -1 }],
  thalion: [{ label: "Guardar o segredo da raiz", effect: "O Círculo Élfico reconhece sua prudência.", faction: "Círculo Élfico", amount: 2 }, { label: "Levar o aviso à vila", effect: "A Vila de Musgo prepara defesas contra o que vem da mata.", faction: "Vila de Musgo", amount: 1 }],
  nix: [{ label: "Abrir uma rota de troca", effect: "A Liga dos Mercadores começa a acompanhar seu nome.", faction: "Liga dos Mercadores", amount: 2 }, { label: "Pedir auxílio aos clãs", effect: "Os Clãs Monstruosos veem que você não esqueceu os seus.", faction: "Clãs Monstruosos", amount: 2 }],
};

const initialEnemies = (): Enemy[] => [
  { id: "wolf-1", x: 13.5, y: 7.8, health: 3, maxHealth: 3, kind: "wolf", alive: true, hurt: 0, phase: 0 },
  { id: "wolf-2", x: 16.7, y: 10.6, health: 3, maxHealth: 3, kind: "wolf", alive: true, hurt: 0, phase: 1.2 },
  { id: "wolf-3", x: 22.5, y: 6.5, health: 3, maxHealth: 3, kind: "wolf", alive: true, hurt: 0, phase: 2.4 },
  { id: "boar-1", x: 9.1, y: 20.5, health: 2, maxHealth: 2, kind: "boar", alive: true, hurt: 0, phase: .7 },
  { id: "goblin-1", x: 33.5, y: 11.5, health: 2, maxHealth: 2, kind: "goblin", alive: true, hurt: 0, phase: 1.9 },
];

const gatherNodes = [
  { id: "root-1", x: 8.6, y: 17.2, kind: "wood" as const }, { id: "root-2", x: 21.8, y: 24.4, kind: "wood" as const },
  { id: "ore-1", x: 29.6, y: 14.7, kind: "ore" as const }, { id: "ore-2", x: 35.2, y: 18.1, kind: "ore" as const },
];

type WorldState = { player: Player; enemies: Enemy[]; essences: Essence[]; gathered: Set<string>; notice: string; quest: string; buildings: string[]; resources: { wood: number; ore: number; food: number; gold: number }; reputation: Record<string, number> };
const worldSaveKey = "aetherion-world-v2";
const freshWorld = (stats: Stats): WorldState => ({ player: { x: 20, y: 20, health: 70 + stats.vitality * 7, maxHealth: 70 + stats.vitality * 7, focus: 100, maxFocus: 100, level: 1, xp: 0, essence: 0, facing: 1, attack: 0, special: 0, invulnerable: 0, evolved: false, potions: 2 }, enemies: initialEnemies(), essences: [], gathered: new Set(), notice: "Mira espera na Vila de Musgo. A trilha norte está tomada por Lobos Primordiais.", quest: "Expulse os Lobos Primordiais da trilha norte", buildings: ["Cabana"], resources: { wood: 20, ore: 8, food: 12, gold: 15 }, reputation: { "Vila de Musgo": 0, "Ordem da Vigília": 0, "Círculo Élfico": 0, "Liga dos Mercadores": 0, "Clãs Monstruosos": 0 } });
const profileKey = (profile: CharacterProfile) => `${profile.raceId}:${profile.classId}:${profile.originId}:${profile.name}`;
const hydrateWorld = (profile: CharacterProfile, stats: Stats): WorldState => { const fresh = freshWorld(stats); try { const saved = JSON.parse(localStorage.getItem(worldSaveKey) ?? "null"); if (!saved || saved.profile !== profileKey(profile)) return fresh; return { ...fresh, ...saved.state, player: { ...fresh.player, ...saved.state.player }, gathered: new Set(saved.state.gathered ?? []), enemies: saved.state.enemies ?? fresh.enemies, essences: saved.state.essences ?? [] }; } catch { return fresh; } };
const persistWorld = (profile: CharacterProfile, world: WorldState) => localStorage.setItem(worldSaveKey, JSON.stringify({ profile: profileKey(profile), state: { ...world, gathered: Array.from(world.gathered) } }));

const distance = (a: { x: number; y: number }, b: { x: number; y: number }) => Math.hypot(a.x - b.x, a.y - b.y);
const clamp = (n: number, min: number, max: number) => Math.max(min, Math.min(max, n));
const hash = (x: number, y: number) => Math.abs(Math.sin(x * 127.1 + y * 311.7) * 43758.5453) % 1;
const terrain = (x: number, y: number) => {
  if (x < 0 || y < 0 || x >= WORLD_W || y >= WORLD_H) return "void";
  if ((x > 1 && x < 7 && y > 3 && y < 12) || (x > 34 && y > 6 && y < 14)) return "water";
  if (x >= 25 && x <= 34 && y >= 18 && y <= 26) return "village";
  if ((x >= 17 && x <= 19) || (y >= 19 && y <= 21 && x >= 18 && x <= 30)) return "path";
  return "grass";
};
const isTree = (x: number, y: number) => terrain(x, y) === "grass" && hash(x, y) > .82 && !((x > 10 && x < 25 && y > 5 && y < 14) || (x > 8 && x < 16 && y > 17 && y < 22));

function drawTree(ctx: CanvasRenderingContext2D, x: number, y: number, s: number) {
  ctx.save(); ctx.translate(x, y);
  ctx.fillStyle = "#3c2a1a"; ctx.fillRect(-s * .08, 0, s * .16, s * .48);
  ctx.fillStyle = "#164437"; ctx.beginPath(); ctx.arc(0, -s * .25, s * .45, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = "#1c6047"; ctx.beginPath(); ctx.arc(-s * .2, -s * .32, s * .27, 0, Math.PI * 2); ctx.arc(s * .21, -s * .3, s * .3, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = "rgba(142,197,113,.32)"; ctx.beginPath(); ctx.arc(-s * .13, -s * .43, s * .12, 0, Math.PI * 2); ctx.fill(); ctx.restore();
}

function drawBuilding(ctx: CanvasRenderingContext2D, x: number, y: number, s: number, kind: "hut" | "forge" | "stall") {
  ctx.save(); ctx.translate(x, y); ctx.fillStyle = "rgba(5,14,16,.35)"; ctx.beginPath(); ctx.ellipse(0, s * .25, s * .7, s * .18, 0, 0, Math.PI * 2); ctx.fill();
  ctx.fillStyle = kind === "forge" ? "#45505a" : "#7c5234"; ctx.fillRect(-s * .55, -s * .12, s * 1.1, s * .52);
  ctx.fillStyle = kind === "stall" ? "#a76b49" : "#b27b4f"; ctx.beginPath(); ctx.moveTo(-s * .68, -s * .12); ctx.lineTo(0, -s * .66); ctx.lineTo(s * .68, -s * .12); ctx.closePath(); ctx.fill();
  ctx.fillStyle = "#172b2b"; ctx.fillRect(-s * .14, s * .09, s * .28, s * .31); if (kind === "forge") { ctx.fillStyle = "#e7bd58"; ctx.beginPath(); ctx.arc(s * .23, s * .16, s * .11, 0, Math.PI * 2); ctx.fill(); } ctx.restore();
}

function drawPerson(ctx: CanvasRenderingContext2D, x: number, y: number, s: number, raceId: string, classAccent: string, moving: number, facing: number) {
  ctx.save(); ctx.translate(x, y + Math.sin(moving) * 2); ctx.scale(facing < 0 ? -1 : 1, 1);
  const race = races.find((item) => item.id === raceId) ?? races[0];
  ctx.fillStyle = "rgba(4,12,16,.35)"; ctx.beginPath(); ctx.ellipse(0, s * .39, s * .32, s * .08, 0, 0, Math.PI * 2); ctx.fill();
  if (raceId === "slime") {
    ctx.fillStyle = race.palette.skin; ctx.strokeStyle = "#153f39"; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(-s * .35, s * .27); ctx.bezierCurveTo(-s * .45, -s * .1, -s * .22, -s * .45, 0, -s * .48); ctx.bezierCurveTo(s * .27, -s * .43, s * .46, -s * .08, s * .33, s * .27); ctx.closePath(); ctx.fill(); ctx.stroke();
    ctx.strokeStyle = "#e7bd58"; ctx.lineWidth = 3; ctx.beginPath(); ctx.moveTo(0, -s * .28); ctx.lineTo(-s * .09, -s * .01); ctx.lineTo(s * .09, s * .13); ctx.stroke(); ctx.fillStyle = "#112e2b"; ctx.beginPath(); ctx.arc(-s * .11, -s * .08, 2, 0, Math.PI * 2); ctx.arc(s * .12, -s * .08, 2, 0, Math.PI * 2); ctx.fill();
  } else {
    ctx.fillStyle = race.palette.cloak; ctx.strokeStyle = "#15242b"; ctx.lineWidth = 3; ctx.fillRect(-s * .22, -s * .02, s * .44, s * .38); ctx.strokeRect(-s * .22, -s * .02, s * .44, s * .38);
    ctx.fillStyle = race.palette.skin; ctx.beginPath(); ctx.arc(0, -s * .24, s * .2, 0, Math.PI * 2); ctx.fill(); ctx.stroke();
    ctx.fillStyle = "#1c2d38"; ctx.beginPath(); ctx.arc(0, -s * .31, s * .21, Math.PI, Math.PI * 2); ctx.fill();
    if (["elf", "wolfkin", "beastfolk", "kobold", "lizard"].includes(raceId)) { ctx.fillStyle = race.palette.cloak; ctx.beginPath(); ctx.moveTo(-s * .14, -s * .39); ctx.lineTo(-s * .22, -s * .62); ctx.lineTo(s * .01, -s * .42); ctx.moveTo(s * .1, -s * .42); ctx.lineTo(s * .24, -s * .62); ctx.lineTo(s * .2, -s * .32); ctx.fill(); }
    ctx.strokeStyle = classAccent; ctx.lineWidth = 4; ctx.beginPath(); ctx.moveTo(s * .22, s * .12); ctx.lineTo(s * .49, -s * .38); ctx.stroke();
  }
  ctx.restore();
}

function drawCreature(ctx: CanvasRenderingContext2D, x: number, y: number, s: number, kind: EnemyKind, phase: number, hurt: number) {
  ctx.save(); ctx.translate(x, y + Math.sin(phase * 4) * 1.5); ctx.fillStyle = "rgba(4,12,16,.38)"; ctx.beginPath(); ctx.ellipse(0, s * .28, s * .48, s * .1, 0, 0, Math.PI * 2); ctx.fill();
  const flash = hurt > 0 ? "#ffdbbc" : kind === "wolf" ? "#56686d" : kind === "boar" ? "#6a4635" : "#49704a";
  ctx.fillStyle = flash; ctx.strokeStyle = "#17252b"; ctx.lineWidth = 3;
  if (kind === "wolf") { ctx.beginPath(); ctx.ellipse(0, 0, s * .46, s * .26, 0, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.beginPath(); ctx.moveTo(-s * .25, -s * .13); ctx.lineTo(-s * .17, -s * .42); ctx.lineTo(-s * .04, -s * .15); ctx.moveTo(s * .08, -s * .15); ctx.lineTo(s * .19, -s * .43); ctx.lineTo(s * .29, -s * .1); ctx.fill(); }
  if (kind === "boar") { ctx.beginPath(); ctx.ellipse(0, 0, s * .47, s * .31, 0, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = "#e6ddc3"; ctx.fillRect(s * .32, s * .02, s * .22, s * .04); }
  if (kind === "goblin") { ctx.beginPath(); ctx.arc(0, -s * .12, s * .25, 0, Math.PI * 2); ctx.fill(); ctx.stroke(); ctx.fillStyle = "#765039"; ctx.fillRect(-s * .22, s * .07, s * .44, s * .28); }
  ctx.fillStyle = "#e7bd58"; ctx.beginPath(); ctx.arc(s * .22, -s * .06, 2.7, 0, Math.PI * 2); ctx.fill(); ctx.restore();
}

function MenuWindow({ menu, close, profile, stats, buildings, potions, build, beginDungeon }: { menu: Menu; close: () => void; profile: CharacterProfile; stats: Stats; buildings: string[]; potions: number; build: (name: string) => void; beginDungeon: () => void }) {
  if (menu === "none") return null;
  if (menu === "dungeon") return <aside className="rpg-menu-window expedition-window"><button className="menu-close" onClick={close}>×</button><p className="menu-overline">DUNGEON · FLORESTA PRIMORDIAL</p><h2>Ruínas da Raiz Silenciosa</h2><p>Uma fissura aberta sob as raízes antigas conduz a um santuário onde a primeira memória da Árvore Primordial foi acorrentada.</p><div className="dungeon-facts"><span><b>AMEAÇA</b> Guardião da Raiz</span><span><b>RECOMPENSA</b> Fragmento Primordial</span><span><b>VÍNCULO</b> Círculo Élfico</span></div><button className="expedition-button" onClick={beginDungeon}>ENTRAR NA FISSURA <span>↗</span></button><small className="dungeon-note">As dungeons alimentam a rota do Novo Deus e abrem regiões mais perigosas.</small></aside>;
  const race = races.find((item) => item.id === profile.raceId)!;
  const playerClass = classes.find((item) => item.id === profile.classId)!;
  const content = menu === "character" ? <><div className="menu-portrait"><CharacterPreview profile={profile} size="small" /></div><h2>{profile.name}</h2><p>{race.name} · {playerClass.name} · {race.talent}</p><div className="detail-stats">{Object.entries(stats).map(([label, value]) => <span key={label}><small>{label}</small><b>{value}</b></span>)}</div><h3>Linhas de evolução</h3><ol>{race.evolution.map((item) => <li key={item}>{item}</li>)}</ol></> : menu === "inventory" ? <><h2>Bolsa de viagem</h2><p>Equipamento e recursos carregados pelo seu eco.</p><div className="item-grid"><span>◈ Núcleo de Essência <b>1</b></span><span>✦ Poção de musgo <b>{potions}</b></span><span>⌁ Madeira viva <b>coletável</b></span><span>◆ Minério de raiz <b>coletável</b></span></div><h3>Equipamento inicial</h3><p><b>{playerClass.weapon}</b> · Manto de viagem · item da origem. Use <b>H</b> para consumir uma poção.</p><h3>Habilidade de classe</h3><p><b>{playerClass.skills[0]}</b> — use <b>R</b> para liberar uma descarga de Éter quando o foco estiver cheio.</p></> : menu === "map" ? <><h2>Mapa de Aetherion</h2><p>O continente responde às escolhas do seu personagem.</p><div className="region-map">{regions.map((region, index) => <span key={region.name} className={region.state}><i>{index + 1}</i><b>{region.name}</b><small>{region.threat}</small></span>)}</div></> : menu === "quests" ? <><h2>Crônicas e escolhas</h2><div className="quest-log"><article><small>PRÓLOGO ATIVO</small><b>O Lobo e a Raiz</b><p>Expulse os Lobos Primordiais da trilha norte e leve a primeira essência à Vila de Musgo.</p></article><article><small>ORIGEM</small><b>{profile.name}</b><p>A origem escolhida vai definir sua primeira aliança e o primeiro título.</p></article><article><small>FINAIS POSSÍVEIS</small><p>{endings.join(" · ")}</p></article></div></> : menu === "codex" ? <><h2>Codex da Grande Ruptura</h2><h3>Dragões Primordiais</h3><div className="codex-row">{primordialDragons.map((dragon) => <span key={dragon}>◉ {dragon}</span>)}</div><h3>Facções</h3><p>Reino Humano · Clãs Monstruosos · Círculo Élfico · Ordem da Vigília · Liga dos Mercadores.</p></> : <><h2>Vila de Musgo</h2><p>Transforme o refúgio em uma civilização. Construções alteram recursos, segurança e missões disponíveis.</p><div className="build-list">{["Cabana", "Horta de musgo", "Forja", "Torre de vigia", "Santuário do Éter"].map((name) => <button key={name} disabled={buildings.includes(name)} onClick={() => build(name)}>{buildings.includes(name) ? "✓ " : "+ "}{name}<small>{name === "Forja" ? "8 minério" : "12 madeira"}</small></button>)}</div></>;
  return <aside className="rpg-menu-window"><button className="menu-close" onClick={close}>×</button><p className="menu-overline">REGISTRO DE AETHERION</p>{content}</aside>;
}

export default function RpgWorldCanvas({ profile, onReturnToCreation }: { profile: CharacterProfile; onReturnToCreation: () => void }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const startingStats = profileStats(profile); const stateRef = useRef<WorldState>(hydrateWorld(profile, startingStats));
  const [hud, setHud] = useState<Hud>(() => ({ health: stateRef.current.player.health, maxHealth: stateRef.current.player.maxHealth, focus: 100, maxFocus: 100, level: 1, xp: 0, essence: 0, potions: 2, wolves: 0, notice: stateRef.current.notice, quest: stateRef.current.quest, menu: "none", buildings: ["Cabana"], wood: 20, ore: 8, food: 12, gold: 15 }));
  const [menu, setMenu] = useState<Menu>("none");
  const [dialogue, setDialogue] = useState<Npc | null>(null);
  const stats = useMemo(() => profileStats(profile), [profile]); const race = races.find((item) => item.id === profile.raceId)!;

  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d"); if (!ctx) return; const keys = new Set<string>(); let frame = 0; let previous = performance.now(); let uiTimer = 0; let saveTimer = 0; let raf = 0;
    const resize = () => { const box = canvas.getBoundingClientRect(); const dpr = Math.min(devicePixelRatio, 2); canvas.width = box.width * dpr; canvas.height = box.height * dpr; ctx.setTransform(dpr, 0, 0, dpr, 0, 0); };
    const keydown = (event: KeyboardEvent) => { if (["Space", "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"].includes(event.code)) event.preventDefault(); keys.add(event.code); if (event.repeat) return; const world = stateRef.current; const player = world.player;
      if (event.code === "Space" && player.attack <= 0) { player.attack = .33; const targets = world.enemies.filter((enemy) => enemy.alive && distance(player, enemy) < 1.45); if (!targets.length) world.notice = "A lâmina encontrou apenas névoa. Aproxime-se da criatura."; targets.forEach((enemy) => { enemy.health -= 1 + (stats.power >= 9 ? 1 : 0); enemy.hurt = .18; if (enemy.health <= 0) { enemy.alive = false; world.essences.push({ id: `essence-${enemy.id}`, x: enemy.x, y: enemy.y, phase: 0 }); world.player.xp += 12; world.notice = `${enemy.kind === "wolf" ? "Lobo Primordial" : "Criatura"} dissipado. A essência responde ao seu eco.`; } }); }
      if (event.code === "KeyF") { const essence = world.essences.find((item) => distance(player, item) < 1.1); const node = gatherNodes.find((item) => !world.gathered.has(item.id) && distance(player, item) < 1.1); if (essence) { world.essences = world.essences.filter((item) => item.id !== essence.id); player.essence += 1; if (player.essence >= 3 && !player.evolved) { player.evolved = true; world.notice = `Evolução iniciada: ${race.evolution[0]} desperta dentro de você.`; } else world.notice = "A essência se mistura à sua forma."; } else if (node) { world.gathered.add(node.id); world.resources[node.kind] += 4; world.notice = node.kind === "wood" ? "Madeira viva coletada para a Vila de Musgo." : "Minério de raiz coletado. A forja pode usar isso."; } else world.notice = "Nenhuma essência ou recurso está ao alcance."; }
      if (event.code === "KeyH") { if (player.potions > 0 && player.health < player.maxHealth) { player.potions -= 1; player.health = Math.min(player.maxHealth, player.health + 28 + stats.resolve * 2); world.notice = "A poção de musgo recompõe sua forma."; } else world.notice = player.potions ? "Sua vitalidade já está plena." : "A bolsa não guarda mais poções."; }
      if (event.code === "KeyR" && player.special <= 0) { if (player.focus < 35) world.notice = "O foco de Éter ainda não responde."; else { player.focus -= 35; player.special = .62; const classInfo = classes.find((item) => item.id === profile.classId)!; const targets = world.enemies.filter((enemy) => enemy.alive && distance(player, enemy) < 2.7); targets.forEach((enemy) => { enemy.health -= 1 + Math.floor(stats.ether / 4); enemy.hurt = .25; if (enemy.health <= 0) { enemy.alive = false; world.essences.push({ id: `essence-${enemy.id}`, x: enemy.x, y: enemy.y, phase: 0 }); player.xp += 15; } }); world.notice = `${classInfo.skills[0]} rasga a clareira e alcança ${targets.length || "nenhuma"} criatura.`; } }
      if (event.code === "KeyE") { const npc = Npcs.find((item) => distance(player, item) < 1.45); if (distance(player, { x: 20.2, y: 4.8 }) < 1.45) setMenu("dungeon"); else if (npc) setDialogue(npc); else world.notice = "Nada aqui responde ao seu chamado."; }
      const menuByKey: Record<string, Menu> = { KeyC: "character", KeyI: "inventory", KeyM: "map", KeyQ: "quests", KeyB: "village", KeyJ: "codex" }; if (menuByKey[event.code]) setMenu((old) => old === menuByKey[event.code] ? "none" : menuByKey[event.code]);
    };
    const keyup = (event: KeyboardEvent) => keys.delete(event.code); window.addEventListener("resize", resize); window.addEventListener("keydown", keydown); window.addEventListener("keyup", keyup); resize();
    const emit = () => { const world = stateRef.current; const defeated = world.enemies.filter((enemy) => enemy.kind === "wolf" && !enemy.alive).length; setHud((old) => ({ ...old, health: Math.ceil(world.player.health), maxHealth: world.player.maxHealth, focus: world.player.focus, maxFocus: world.player.maxFocus, level: world.player.level, xp: world.player.xp, essence: world.player.essence, potions: world.player.potions, wolves: defeated, notice: world.notice, quest: defeated >= 3 ? "Leve a essência à Vila de Musgo" : "Expulse os Lobos Primordiais da trilha norte", buildings: [...world.buildings], wood: world.resources.wood, ore: world.resources.ore, food: world.resources.food, gold: world.resources.gold })); };
    const loop = (now: number) => { const delta = Math.min(.05, (now - previous) / 1000); previous = now; frame += delta; const world = stateRef.current; const p = world.player; let mx = 0; let my = 0; if (keys.has("KeyW") || keys.has("ArrowUp")) my -= 1; if (keys.has("KeyS") || keys.has("ArrowDown")) my += 1; if (keys.has("KeyA") || keys.has("ArrowLeft")) mx -= 1; if (keys.has("KeyD") || keys.has("ArrowRight")) mx += 1; if (mx || my) { const len = Math.hypot(mx, my); mx /= len; my /= len; const speed = 3 + stats.agility * .06; const nx = clamp(p.x + mx * speed * delta, 1, WORLD_W - 2); const ny = clamp(p.y + my * speed * delta, 1, WORLD_H - 2); if (!isTree(Math.round(nx), Math.round(ny)) && terrain(Math.round(nx), Math.round(ny)) !== "water") { p.x = nx; p.y = ny; p.facing = mx || p.facing; } }
      p.attack = Math.max(0, p.attack - delta); p.invulnerable = Math.max(0, p.invulnerable - delta); for (const enemy of world.enemies) if (enemy.alive) { enemy.phase += delta; enemy.hurt = Math.max(0, enemy.hurt - delta); const d = distance(enemy, p); if (d < 4.5 && d > .78) { enemy.x += ((p.x - enemy.x) / d) * delta * .38; enemy.y += ((p.y - enemy.y) / d) * delta * .38; } if (d < .85 && p.invulnerable <= 0) { p.health -= 5; p.invulnerable = .7; world.notice = "As garras da floresta encontram sua forma. Reposicione-se."; } }
      world.essences.forEach((item) => item.phase += delta * 3); if (p.health <= 0) { p.health = p.maxHealth; p.x = 25; p.y = 21; world.notice = "A Vila de Musgo recompõe seu eco. A floresta ainda espera."; }
      p.focus = Math.min(p.maxFocus, p.focus + delta * (4 + stats.ether * .12)); p.special = Math.max(0, p.special - delta); if (p.xp >= p.level * 40) { p.xp -= p.level * 40; p.level += 1; p.maxHealth += 8; p.health = p.maxHealth; world.notice = `Nível ${p.level}: sua forma se fortaleceu e um novo eco responde.`; } saveTimer += delta; if (saveTimer > 1.5) { saveTimer = 0; persistWorld(profile, world); } uiTimer += delta; if (uiTimer > .12) { uiTimer = 0; emit(); }
      const width = canvas.clientWidth; const height = canvas.clientHeight; ctx.clearRect(0, 0, width, height); const tile = 56; const camX = p.x; const camY = p.y; const sx = (x: number) => (x - camX) * tile + width / 2; const sy = (y: number) => (y - camY) * tile + height / 2;
      ctx.fillStyle = "#102c27"; ctx.fillRect(0, 0, width, height); const startX = Math.floor(camX - width / tile / 2) - 1; const endX = Math.ceil(camX + width / tile / 2) + 1; const startY = Math.floor(camY - height / tile / 2) - 1; const endY = Math.ceil(camY + height / tile / 2) + 1;
      for (let y = startY; y <= endY; y += 1) for (let x = startX; x <= endX; x += 1) { const t = terrain(x, y); const px = sx(x), py = sy(y); ctx.fillStyle = t === "water" ? "#1b5357" : t === "path" ? "#8b7753" : t === "village" ? "#6b6650" : "#285447"; ctx.fillRect(px, py, tile + 1, tile + 1); if (t === "grass") { ctx.fillStyle = hash(x, y) > .54 ? "#34634d" : "#254d42"; ctx.fillRect(px + 4 + hash(y, x) * 12, py + 8 + hash(x + 3, y) * 18, 2, 5); } if (t === "water") { ctx.strokeStyle = "rgba(165,221,205,.22)"; ctx.beginPath(); ctx.arc(px + tile * .5, py + tile * .5, 10 + Math.sin(frame + x) * 2, 0, Math.PI); ctx.stroke(); } if (t === "path") { ctx.fillStyle = "rgba(55,44,32,.2)"; ctx.fillRect(px + 1, py + 1, tile - 2, 2); } }
      for (let y = startY; y <= endY; y += 1) for (let x = startX; x <= endX; x += 1) if (isTree(x, y)) drawTree(ctx, sx(x + .5), sy(y + .44), tile * .9);
      drawBuilding(ctx, sx(27.1), sy(21.4), tile * .9, "hut"); drawBuilding(ctx, sx(30.2), sy(22.5), tile * .78, "stall"); if (world.buildings.includes("Horta de musgo")) { ctx.fillStyle = "#387d53"; ctx.fillRect(sx(28.8), sy(24.1), tile * 1.3, tile * .62); for (let seed = 0; seed < 7; seed += 1) { ctx.strokeStyle = "#addb73"; ctx.beginPath(); ctx.moveTo(sx(29) + seed * 8, sy(24.58)); ctx.lineTo(sx(29) + seed * 8, sy(24.28)); ctx.stroke(); } } if (world.buildings.includes("Forja")) drawBuilding(ctx, sx(26.3), sy(24.2), tile * .72, "forge"); if (world.buildings.includes("Torre de vigia")) { ctx.fillStyle = "#593d2c"; ctx.fillRect(sx(32.6), sy(19.7), 8, tile * 1.1); ctx.fillStyle = "#a6784f"; ctx.beginPath(); ctx.moveTo(sx(32.1), sy(19.7)); ctx.lineTo(sx(32.6) + 4, sy(19.05)); ctx.lineTo(sx(33.1), sy(19.7)); ctx.closePath(); ctx.fill(); } if (world.buildings.includes("Santuário do Éter")) { ctx.strokeStyle = "#e7bd58"; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(sx(24.6), sy(22.9), 13 + Math.sin(frame * 2) * 2, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = "#77dbb5"; ctx.beginPath(); ctx.arc(sx(24.6), sy(22.9), 4, 0, Math.PI * 2); ctx.fill(); } ctx.save(); ctx.translate(sx(20.2), sy(4.8)); ctx.fillStyle = "rgba(116,223,183,.17)"; ctx.beginPath(); ctx.ellipse(0, 0, 23, 31, 0, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = "#e7bd58"; ctx.lineWidth = 3; ctx.beginPath(); ctx.ellipse(0, 0, 11, 20, 0, 0, Math.PI * 2); ctx.stroke(); ctx.fillStyle = "#7fe0be"; ctx.beginPath(); ctx.arc(0, 0, 5 + Math.sin(frame * 3) * 2, 0, Math.PI * 2); ctx.fill(); ctx.restore();
      const ySorted = [ ...Npcs.map((npc) => ({ y: npc.y, render: () => drawPerson(ctx, sx(npc.x), sy(npc.y), tile * .48, npc.race, "#e7bd58", frame + npc.x, 1) })), ...world.enemies.filter((enemy) => enemy.alive).map((enemy) => ({ y: enemy.y, render: () => { drawCreature(ctx, sx(enemy.x), sy(enemy.y), tile * .48, enemy.kind, enemy.phase, enemy.hurt); const hp = enemy.health / enemy.maxHealth; ctx.fillStyle = "rgba(7,18,19,.8)"; ctx.fillRect(sx(enemy.x) - 14, sy(enemy.y) - 35, 28, 4); ctx.fillStyle = "#d85f59"; ctx.fillRect(sx(enemy.x) - 14, sy(enemy.y) - 35, 28 * hp, 4); } })), { y: p.y, render: () => { drawPerson(ctx, sx(p.x), sy(p.y), tile * .58, profile.raceId, race.palette.accent, frame * 9 * (mx || my ? 1 : .2), p.facing); if (p.attack > 0) { ctx.strokeStyle = race.palette.accent; ctx.lineWidth = 5; ctx.globalAlpha = p.attack / .33; ctx.beginPath(); ctx.arc(sx(p.x), sy(p.y), tile * .62, -1.1, 1.1); ctx.stroke(); ctx.globalAlpha = 1; } } } ];
      gatherNodes.filter((node) => !world.gathered.has(node.id)).forEach((node) => { const nx = sx(node.x), ny = sy(node.y); ctx.fillStyle = node.kind === "wood" ? "#5b9a5a" : "#758da2"; ctx.beginPath(); ctx.arc(nx, ny, 9, 0, Math.PI * 2); ctx.fill(); ctx.strokeStyle = node.kind === "wood" ? "#b7dd75" : "#c8d7df"; ctx.lineWidth = 2; ctx.beginPath(); ctx.moveTo(nx - 5, ny + 4); ctx.lineTo(nx + 3, ny - 6); ctx.stroke(); }); world.essences.forEach((essence) => { const ex = sx(essence.x), ey = sy(essence.y) - 13 - Math.sin(essence.phase) * 5; ctx.fillStyle = "rgba(231,189,88,.16)"; ctx.beginPath(); ctx.arc(ex, ey, 15, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = "#e7bd58"; ctx.beginPath(); ctx.moveTo(ex, ey - 8); ctx.lineTo(ex + 6, ey); ctx.lineTo(ex, ey + 8); ctx.lineTo(ex - 6, ey); ctx.closePath(); ctx.fill(); }); ySorted.sort((a, b) => a.y - b.y).forEach((item) => item.render()); if (p.special > 0) { ctx.strokeStyle = race.palette.accent; ctx.globalAlpha = p.special / .62; ctx.lineWidth = 3; ctx.beginPath(); ctx.arc(sx(p.x), sy(p.y), tile * (1.8 - p.special), 0, Math.PI * 2); ctx.stroke(); ctx.globalAlpha = 1; }
      const nearby = Npcs.find((npc) => distance(p, npc) < 1.5); const nearGate = distance(p, { x: 20.2, y: 4.8 }) < 1.45; if (nearby || nearGate) { const tx = nearby ? sx(nearby.x) : sx(20.2); const ty = nearby ? sy(nearby.y) : sy(4.8); ctx.fillStyle = "rgba(6,21,21,.78)"; ctx.fillRect(tx - 38, ty - 68, 76, 17); ctx.fillStyle = "#e7bd58"; ctx.font = "10px Manrope"; ctx.textAlign = "center"; ctx.fillText(nearGate ? "[E] ENTRAR" : "[E] FALAR", tx, ty - 56); }
      ctx.fillStyle = "rgba(2,10,13,.38)"; const vignette = ctx.createRadialGradient(width / 2, height / 2, Math.min(width, height) * .26, width / 2, height / 2, Math.max(width, height) * .8); vignette.addColorStop(0, "transparent"); vignette.addColorStop(1, "rgba(3,13,15,.68)"); ctx.fillStyle = vignette; ctx.fillRect(0, 0, width, height); raf = requestAnimationFrame(loop); };
    raf = requestAnimationFrame(loop); return () => { persistWorld(profile, stateRef.current); cancelAnimationFrame(raf); window.removeEventListener("resize", resize); window.removeEventListener("keydown", keydown); window.removeEventListener("keyup", keyup); };
    }, [profile, race.palette.accent, race.evolution, race.talent, stats.agility, stats.power, stats.ether, stats.resolve]);
  const build = (name: string) => { const world = stateRef.current; const plans: Record<string, { wood: number; ore: number; food: number; effect: string }> = { "Cabana": { wood: 12, ore: 0, food: 0, effect: "Novos viajantes encontram abrigo." }, "Horta de musgo": { wood: 10, ore: 0, food: 0, effect: "A horta passa a produzir alimento para a vila." }, "Forja": { wood: 12, ore: 8, food: 0, effect: "A forja melhora o equipamento das expedições." }, "Torre de vigia": { wood: 15, ore: 2, food: 0, effect: "A torre revela ameaças próximas no mapa." }, "Santuário do Éter": { wood: 8, ore: 4, food: 0, effect: "O santuário estabiliza a evolução e o foco." } }; const plan = plans[name]; if (world.resources.wood < plan.wood || world.resources.ore < plan.ore || world.resources.food < plan.food) { world.notice = "Recursos insuficientes. Colete madeira, minério ou alimento antes de construir."; return; } world.resources.wood -= plan.wood; world.resources.ore -= plan.ore; world.resources.food -= plan.food; if (name === "Horta de musgo") world.resources.food += 8; if (name === "Santuário do Éter") { world.player.focus = world.player.maxFocus; world.player.essence += 1; } if (name === "Forja") world.player.potions += 1; world.buildings.push(name); world.notice = `${name} erguido. ${plan.effect}`; };
  const beginDungeon = () => { const world = stateRef.current; if (world.enemies.some((enemy) => enemy.id === "root-guardian" && enemy.alive)) { world.notice = "O Guardião da Raiz já espera por você na clareira."; setMenu("none"); return; } world.enemies.push({ id: "root-guardian", x: 21.4, y: 6.2, health: 12, maxHealth: 12, kind: "wolf", alive: true, hurt: 0, phase: 0 }); world.quest = "Derrote o Guardião da Raiz e recupere o Fragmento Primordial"; world.notice = "O Guardião da Raiz desperta. Sua história entrou na primeira dungeon."; setMenu("none"); };
  const world = stateRef.current;
  const chooseDialogue = (choice: { label: string; effect: string; faction: string; amount: number }) => { world.reputation[choice.faction] = (world.reputation[choice.faction] ?? 0) + choice.amount; world.notice = `${choice.effect} Reputação com ${choice.faction}: ${world.reputation[choice.faction] > 0 ? "+" : ""}${world.reputation[choice.faction]}.`; setDialogue(null); };
  return <main className="rpg-shell"><canvas ref={canvasRef} className="rpg-canvas" aria-label="Mapa 2D explorável da Floresta Primordial" />
    <header className="rpg-topbar"><div className="world-brand"><span>✦</span><div><small>ECOS DE AETHERION</small><b>FLORESTA PRIMORDIAL</b></div></div><div className="world-resources"><span>⌁ {hud.wood}</span><span>◆ {hud.ore}</span><span>◒ {hud.food}</span><span>¤ {hud.gold}</span></div><button onClick={onReturnToCreation} title="Editar personagem">RECRIAR ECO</button></header>
    <section className="player-hud"><div className="hud-name"><small>NÍVEL {hud.level}</small><b>{profile.name}</b><span>{race.name} · {classes.find((item) => item.id === profile.classId)?.name}</span></div><div className="life-bar"><i style={{ width: `${hud.health / hud.maxHealth * 100}%` }} /></div><div className="focus-bar"><i style={{ width: `${hud.focus / hud.maxFocus * 100}%` }} /></div><div className="hud-numbers"><span>VIDA {hud.health}/{hud.maxHealth}</span><span>FOCO {Math.ceil(hud.focus)}</span><span>ESSÊNCIA {hud.essence}</span></div></section>
    <section className="quest-hud"><small>MISSÃO ATIVA</small><b>{hud.quest}</b><p>{hud.wolves}/3 Lobos Primordiais dissipados · {hud.notice}</p></section>
    <nav className="rpg-actions" aria-label="Menus do RPG"><button onClick={() => setMenu("character")}><kbd>C</kbd><span>Eco</span></button><button onClick={() => setMenu("inventory")}><kbd>I</kbd><span>Bolsa</span></button><button onClick={() => setMenu("map")}><kbd>M</kbd><span>Mapa</span></button><button onClick={() => setMenu("quests")}><kbd>Q</kbd><span>Crônicas</span></button><button onClick={() => setMenu("village")}><kbd>B</kbd><span>Vila</span></button><button onClick={() => setMenu("codex")}><kbd>J</kbd><span>Codex</span></button></nav>
    <footer className="world-controls"><span><kbd>WASD</kbd> mover</span><span><kbd>ESPAÇO</kbd> atacar</span><span><kbd>R</kbd> técnica</span><span><kbd>F</kbd> absorver/coletar</span><span><kbd>H</kbd> curar</span><span><kbd>E</kbd> conversar</span></footer>
    <MenuWindow menu={menu} close={() => setMenu("none")} profile={profile} stats={stats} buildings={hud.buildings} potions={hud.potions} build={build} beginDungeon={beginDungeon} />
    {dialogue && <div className="dialogue-box"><button onClick={() => setDialogue(null)}>×</button><small>{dialogue.role.toUpperCase()}</small><h2>{dialogue.name}</h2><p>“{dialogue.line}”</p><div><b>NOVO VÍNCULO</b><span>{dialogue.quest}</span></div><section className="dialogue-choices">{dialogueChoices[dialogue.id].map((choice) => <button key={choice.label} onClick={() => chooseDialogue(choice)}><b>{choice.label}</b><span>{choice.effect}</span></button>)}</section><em>Escolhas mudam sua reputação e rotas de missão.</em></div>}
  </main>;
}
