/**
 * Linha dos Ecos — o mapa é desenhado em tiles no canvas: chão, árvores, criaturas e heróis são entidades 2D reais.
 * Nenhuma imagem de cenário ou marcador geométrico participa do campo de jogo.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import { classes, endings, primordialDragons, races, regions, type Stats } from "../game/content";
import { TILE_PX, endingRequirements, quests } from "../game/campaign";
import type { CharacterProfile } from "./RpgGame";
import { CharacterPreview, profileStats } from "./RpgGame";

type EnemyKind = "wolf" | "boar" | "goblin";
type Enemy = { id: string; x: number; y: number; health: number; maxHealth: number; kind: EnemyKind; alive: boolean; hurt: number; phase: number; attack?: number; guard?: number; death?: number };
type Essence = { id: string; x: number; y: number; phase: number };
type CombatText = { id: string; x: number; y: number; text: string; color: string; life: number; maxLife: number; scale: number };
type Player = { x: number; y: number; health: number; maxHealth: number; focus: number; maxFocus: number; level: number; xp: number; essence: number; facing: number; attack: number; special: number; invulnerable: number; evolved: boolean; potions: number };
type Npc = { id: string; name: string; role: string; x: number; y: number; race: "human" | "elf" | "goblin"; line: string; quest: string };
type Menu = "none" | "character" | "inventory" | "map" | "quests" | "village" | "codex" | "dungeon";
type Hud = { health: number; maxHealth: number; focus: number; maxFocus: number; level: number; xp: number; essence: number; potions: number; wolves: number; notice: string; quest: string; menu: Menu; buildings: string[]; wood: number; ore: number; food: number; gold: number; playerX: number; playerY: number };

const WORLD_W = 42;
const WORLD_H = 30;
const Npcs: Npc[] = [
  { id: "mira", name: "Mira de Musgo", role: "Guardião da vila", x: 28.5, y: 20.1, race: "human", line: "Os lobos foram tocados pela Ruptura. A vila não quer caçadores: quer alguém que entenda o Éter.", quest: "Expulse os Lobos Primordiais da trilha norte." },
  { id: "thalion", name: "Thalion", role: "Emissário élfico", x: 19.7, y: 8.4, race: "elf", line: "A Árvore Primordial ainda sonha. Não confunda silêncio com paz.", quest: "Escute os espíritos da raiz antiga." },
  { id: "nix", name: "Nix", role: "Mercador goblin", x: 31.4, y: 23.2, race: "goblin", line: "Eu vendo coisas honestas. As desonestas custam mais, mas são muito mais interessantes.", quest: "Troque recursos para fortalecer a Vila de Musgo." },
];

const dialogueChoices: Record<string, { label: string; effect: string; faction: string; amount: number }[]> = {
  mira: [{ label: "Defender a Vila de Musgo", effect: "A vila passa a confiar no seu eco.", faction: "Vila de Musgo", amount: 2 }, { label: "Perguntar pela Ordem da Vigília", effect: "Você descobre que a Ordem esconde informações sobre a Ruptura.", faction: "Ordem da Vigília", amount: -1 }],
  thalion: [{ label: "Guardar o segredo da raiz", effect: "O Círculo Élfico reconhece sua prudência.", faction: "Círculo Élfico", amount: 2 }, { label: "Levar o aviso à vila", effect: "A Vila de Musgo prepara defesas contra o que vem da mata.", faction: "Vila de Musgo", amount: 1 }],
  nix: [{ label: "Abrir uma rota de troca", effect: "A Liga dos Mercadores começa a acompanhar seu nome.", faction: "Liga dos Mercadores", amount: 2 }, { label: "Pedir auxílio aos clãs", effect: "Os Clãs Monstruosos veem que você não esqueceu os seus.", faction: "Clãs Monstruosos", amount: 2 }],
};

const initialEnemies = (): Enemy[] => [
  { id: "wolf-1", x: 13.5, y: 7.8, health: 3, maxHealth: 3, kind: "wolf", alive: true, hurt: 0, phase: 0, attack: 0, guard: 0, death: 0 },
  { id: "wolf-2", x: 16.7, y: 10.6, health: 3, maxHealth: 3, kind: "wolf", alive: true, hurt: 0, phase: 1.2, attack: 0, guard: 0, death: 0 },
  { id: "wolf-3", x: 22.5, y: 6.5, health: 3, maxHealth: 3, kind: "wolf", alive: true, hurt: 0, phase: 2.4, attack: 0, guard: 0, death: 0 },
  { id: "boar-1", x: 9.1, y: 20.5, health: 2, maxHealth: 2, kind: "boar", alive: true, hurt: 0, phase: .7, attack: 0, guard: 0, death: 0 },
  { id: "goblin-1", x: 33.5, y: 11.5, health: 2, maxHealth: 2, kind: "goblin", alive: true, hurt: 0, phase: 1.9, attack: 0, guard: 0, death: 0 },
];

const gatherNodes = [
  { id: "root-1", x: 8.6, y: 17.2, kind: "wood" as const }, { id: "root-2", x: 21.8, y: 24.4, kind: "wood" as const },
  { id: "ore-1", x: 29.6, y: 14.7, kind: "ore" as const }, { id: "ore-2", x: 35.2, y: 18.1, kind: "ore" as const },
];

type WorldState = { player: Player; enemies: Enemy[]; essences: Essence[]; gathered: Set<string>; notice: string; quest: string; buildings: string[]; resources: { wood: number; ore: number; food: number; gold: number }; reputation: Record<string, number> };
const worldSaveKey = "aetherion-world-v2";
const freshWorld = (stats: Stats): WorldState => ({ player: { x: 20, y: 20, health: 70 + stats.vitality * 7, maxHealth: 70 + stats.vitality * 7, focus: 100, maxFocus: 100, level: 1, xp: 0, essence: 0, facing: 1, attack: 0, special: 0, invulnerable: 0, evolved: false, potions: 2 }, enemies: initialEnemies(), essences: [], gathered: new Set(), notice: "Mira espera na Vila de Musgo. A trilha norte está tomada por Lobos Primordiais.", quest: "Expulse os Lobos Primordiais da trilha norte", buildings: ["Cabana"], resources: { wood: 20, ore: 8, food: 12, gold: 15 }, reputation: { "Vila de Musgo": 0, "Ordem da Vigília": 0, "Círculo Élfico": 0, "Liga dos Mercadores": 0, "Clãs Monstruosos": 0 } });
const profileKey = (profile: CharacterProfile) => `${profile.raceId}:${profile.classId}:${profile.originId}:${profile.name}`;
const hydrateWorld = (profile: CharacterProfile, stats: Stats, saveKey = worldSaveKey): WorldState => { const fresh = freshWorld(stats); try { const saved = JSON.parse(localStorage.getItem(saveKey) ?? "null"); if (!saved || saved.profile !== profileKey(profile)) return fresh; return { ...fresh, ...saved.state, player: { ...fresh.player, ...saved.state.player }, gathered: new Set(saved.state.gathered ?? []), enemies: saved.state.enemies ?? fresh.enemies, essences: saved.state.essences ?? [] }; } catch { return fresh; } };
const persistWorld = (profile: CharacterProfile, world: WorldState, saveKey = worldSaveKey) => localStorage.setItem(saveKey, JSON.stringify({ profile: profileKey(profile), state: { ...world, gathered: Array.from(world.gathered) } }));

const distance = (a: { x: number; y: number }, b: { x: number; y: number }) => Math.hypot(a.x - b.x, a.y - b.y);
const clamp = (n: number, min: number, max: number) => Math.max(min, Math.min(max, n));
const hash = (x: number, y: number) => Math.abs(Math.sin(x * 127.1 + y * 311.7) * 43758.5453) % 1;
const terrain = (x: number, y: number) => {
  if (x < 0 || y < 0 || x >= WORLD_W || y >= WORLD_H) return "void";
  if ((x > 1 && x < 7 && y > 3 && y < 12) || (x > 34 && y > 6 && y < 14)) return "water";
  if (x >= 25 && x <= 34 && y >= 18 && y <= 26) return "village";
  if ((x >= 17 && x <= 19) || (y >= 19 && y <= 21 && x >= 18 && x <= 30)) return "path";
  return "grass";
};
const isTree = (x: number, y: number) => terrain(x, y) === "grass" && hash(x, y) > .82 && !((x > 10 && x < 25 && y > 5 && y < 14) || (x > 8 && x < 16 && y > 17 && y < 22));

function drawTree(ctx: CanvasRenderingContext2D, x: number, y: number, s: number) {
  const u = s / 64; const p = (px: number, py: number, w: number, h: number, color: string) => { ctx.fillStyle = color; ctx.fillRect(Math.round(x + px * u), Math.round(y + py * u), Math.ceil(w * u), Math.ceil(h * u)); };
  p(-25, 22, 50, 8, "rgba(3,16,18,.42)"); p(-6, 1, 12, 29, "#38271e"); p(-10, 10, 8, 16, "#523625"); p(2, 6, 7, 19, "#251b17");
  p(-23, -25, 46, 29, "#143c36"); p(-29, -15, 58, 22, "#143c36"); p(-19, -38, 39, 15, "#143c36");
  p(-23, -20, 17, 17, "#1e5c47"); p(-4, -30, 22, 20, "#1f694d"); p(5, -10, 20, 16, "#1d6147"); p(-16, -5, 19, 14, "#276f50");
  p(-14, -25, 8, 5, "#5e995f"); p(3, -31, 9, 6, "#70ad69"); p(12, -16, 7, 5, "#579458"); p(-21, -10, 6, 5, "#4f874f");
}

function drawBuilding(ctx: CanvasRenderingContext2D, x: number, y: number, s: number, kind: "hut" | "forge" | "stall") {
  const u = s / 32; const p = (px: number, py: number, w: number, h: number, color: string) => { ctx.fillStyle = color; ctx.fillRect(Math.round(x + px * u), Math.round(y + py * u), Math.ceil(w * u), Math.ceil(h * u)); };
  const wide = kind === "forge" ? 3 : 2; p(-16 * wide, 15, 32 * wide, 8, "rgba(3,16,18,.48)"); p(-12 * wide, -8, 24 * wide, 25, kind === "forge" ? "#445157" : "#7d5434");
  for (let plank = -10 * wide; plank < 10 * wide; plank += 8) p(plank, -4, 3, 18, "rgba(43,28,20,.42)");
  p(-16 * wide, -16, 32 * wide, 9, kind === "stall" ? "#a85739" : "#a86d44"); p(-11 * wide, -23, 22 * wide, 7, kind === "forge" ? "#56636a" : "#c18150"); p(-6, 5, 12, 12, "#1b2524"); p(-4, 7, 8, 10, "#0d1819");
  if (kind === "forge") { p(8 * wide, 4, 7, 8, "#d66e3d"); p(9 * wide, 5, 5, 5, "#f0be58"); p(-14 * wide, -27, 4, 15, "#2a2c30"); }
  if (kind === "stall") { p(-13 * wide, -5, 26 * wide, 4, "#d6b15a"); p(-8 * wide, -1, 2, 15, "#4d3223"); p(6 * wide, -1, 2, 15, "#4d3223"); }
}

function drawPerson(ctx: CanvasRenderingContext2D, x: number, y: number, s: number, raceId: string, classAccent: string, moving: number, facing: number) {
  const race = races.find((item) => item.id === raceId) ?? races[0]; const u = s / 48; const dir = facing < 0 ? -1 : 1; const bob = Math.round(Math.sin(moving) * 1.5); const p = (px: number, py: number, w: number, h: number, color: string) => { ctx.fillStyle = color; ctx.fillRect(Math.round(x + px * u * dir), Math.round(y + py * u + bob), Math.ceil(w * u * dir), Math.ceil(h * u)); };
  p(-17 * dir, 20, 34 * dir, 5, "rgba(3,15,17,.48)");
  if (raceId === "slime") { p(-15 * dir, -5, 30 * dir, 22, "#153d3a"); p(-12 * dir, -10, 24 * dir, 27, race.palette.skin); p(-8 * dir, -14, 16 * dir, 6, "#71ba94"); p(-6 * dir, -2, 4 * dir, 4, "#102727"); p(5 * dir, -2, 4 * dir, 4, "#102727"); p(-2 * dir, -7, 4 * dir, 15, race.palette.accent); p(-6 * dir, 9, 12 * dir, 5, "rgba(209,246,196,.24)"); return; }
  p(-10 * dir, 7, 8 * dir, 15, "#172126"); p(3 * dir, 7, 8 * dir, 15, "#172126"); p(-14 * dir, 0, 28 * dir, 16, "#15232b"); p(-12 * dir, -2, 24 * dir, 18, race.palette.cloak); p(-15 * dir, 2, 5 * dir, 12, "#29443d"); p(10 * dir, 3, 5 * dir, 12, "#1d332f"); p(-10 * dir, -18, 20 * dir, 18, race.palette.skin); p(-12 * dir, -20, 24 * dir, 7, "#1a2a34"); p(-7 * dir, -13, 4 * dir, 3, "#192222"); p(4 * dir, -13, 4 * dir, 3, "#192222");
  if (["elf", "wolfkin", "beastfolk", "kobold", "lizard"].includes(raceId)) { p(-13 * dir, -20, 5 * dir, 9, race.palette.cloak); p(9 * dir, -20, 5 * dir, 9, race.palette.cloak); }
  p(13 * dir, 1, 5 * dir, 15, race.palette.skin); p(17 * dir, -12, 3 * dir, 30, "#172326"); p(19 * dir, -14, 4 * dir, 20, "#d6c9a4"); p(20 * dir, -12, 3 * dir, 18, classAccent); p(16 * dir, 11, 9 * dir, 3, "#b89448");
}

function drawCreature(ctx: CanvasRenderingContext2D, x: number, y: number, s: number, kind: EnemyKind, phase: number, hurt: number, attack = 0, guard = 0) {
  const u = s / 48; const bob = Math.round(Math.sin(phase * 4) * 1.5); const lunge = attack > 0 ? Math.round((attack / .35) * 7) : 0; const p = (px: number, py: number, w: number, h: number, color: string) => { ctx.fillStyle = color; ctx.fillRect(Math.round(x + px * u + lunge), Math.round(y + py * u + bob), Math.ceil(w * u), Math.ceil(h * u)); }; const base = hurt > 0 ? "#f2d3ac" : kind === "wolf" ? "#596b70" : kind === "boar" ? "#774b38" : "#4d754d";
  p(-19, 16, 38, 5, "rgba(3,15,17,.48)"); if (kind === "wolf") { p(-18, -2, 35, 17, "#27393d"); p(-16, -7, 29, 19, base); p(-13, -17, 7, 12, "#3c5051"); p(5, -17, 7, 12, "#3c5051"); p(10, -4, 10, 9, "#40575a"); p(14, -3, 3, 3, "#e4c65b"); p(-12, 10, 5, 10, "#223137"); p(8, 10, 5, 10, "#223137"); } else if (kind === "boar") { p(-18, -5, 37, 20, "#402a29"); p(-16, -8, 34, 22, base); p(13, -3, 9, 9, "#a26f54"); p(19, 1, 7, 3, "#e8d6ae"); p(-11, 10, 5, 10, "#302226"); p(7, 10, 5, 10, "#302226"); } else { p(-13, -11, 26, 18, "#25452e"); p(-11, -13, 22, 17, base); p(-17, -10, 8, 7, "#5b9253"); p(9, -10, 8, 7, "#5b9253"); p(-14, 5, 28, 15, "#65412f"); p(3, -8, 3, 3, "#f0d15a"); }
  if (attack > 0) { p(18, -13, 12, 4, "#d7c78e"); p(24, -9, 8, 4, "#d7c78e"); } if (guard > 0) { ctx.globalAlpha = Math.min(1, guard * 3); p(-24, -21, 6, 38, "#8bcfb2"); p(-20, -25, 20, 4, "#8bcfb2"); p(-20, 17, 20, 4, "#8bcfb2"); ctx.globalAlpha = 1; }
}

function drawDeath(ctx: CanvasRenderingContext2D, x: number, y: number, phase: number, accent: string) {
  const spread = Math.round((1 - phase / .6) * 20); ctx.globalAlpha = Math.max(.08, phase / .6); ctx.fillStyle = "#263a38"; for (let i = 0; i < 8; i += 1) { const dx = ((i * 13) % 30) - 15; const dy = ((i * 7) % 20) - 10; ctx.fillRect(x + dx + Math.sign(dx) * spread, y + dy + spread, 5, 5); } ctx.fillStyle = accent; ctx.fillRect(x - 4, y - 4 + spread, 8, 8); ctx.globalAlpha = 1;
}

function drawBoss(ctx: CanvasRenderingContext2D, x: number, y: number, phase: number, hurt: number) {
  const u = 1; const p = (px: number, py: number, w: number, h: number, color: string) => { ctx.fillStyle = color; ctx.fillRect(Math.round(x + px * u), Math.round(y + py * u + Math.sin(phase * 3)), w * u, h * u); }; const bark = hurt > 0 ? "#d9c69d" : "#62513b";
  p(-47, 41, 94, 9, "rgba(2,13,15,.54)"); p(-38, -26, 76, 66, "#263c32"); p(-32, -34, 64, 73, bark); p(-47, -15, 18, 51, "#4a3c2e"); p(29, -15, 18, 51, "#4a3c2e"); p(-25, -47, 14, 27, "#506844"); p(11, -47, 14, 27, "#506844"); p(-18, -54, 36, 14, "#263c32"); p(-12, -19, 24, 17, "#142829"); p(-8, -16, 5, 5, "#e7bd58"); p(5, -16, 5, 5, "#e7bd58"); p(-4, -4, 8, 27, "#70b77d"); p(-30, 16, 17, 17, "#3b2e26"); p(14, 16, 17, 17, "#3b2e26");
}

function drawEtherBurst(ctx: CanvasRenderingContext2D, x: number, y: number, phase: number, accent: string) {
  const r = 48 * Math.max(.2, 1 - phase / .62); ctx.globalAlpha = Math.max(.1, phase / .62); ctx.fillStyle = accent; for (let i = 0; i < 12; i += 1) { const a = i * Math.PI / 6; const px = Math.round(x + Math.cos(a) * r); const py = Math.round(y + Math.sin(a) * r); ctx.fillRect(px - 3, py - 3, 6, 6); } ctx.fillStyle = "#d8fff0"; ctx.fillRect(Math.round(x - 5), Math.round(y - 5), 10, 10); ctx.globalAlpha = 1;
}

function MenuWindow({ menu, close, profile, stats, buildings, potions, build, beginDungeon }: { menu: Menu; close: () => void; profile: CharacterProfile; stats: Stats; buildings: string[]; potions: number; build: (name: string) => void; beginDungeon: () => void }) {
  if (menu === "none") return null;
  if (menu === "dungeon") return <aside className="rpg-menu-window expedition-window"><button className="menu-close" onClick={close}>×</button><p className="menu-overline">DUNGEON · FLORESTA PRIMORDIAL</p><h2>Ruínas da Raiz Silenciosa</h2><p>Uma fissura aberta sob as raízes antigas conduz a um santuário onde a primeira memória da Árvore Primordial foi acorrentada.</p><div className="dungeon-facts"><span><b>AMEAÇA</b> Guardião da Raiz</span><span><b>RECOMPENSA</b> Fragmento Primordial</span><span><b>VÍNCULO</b> Círculo Élfico</span></div><button className="expedition-button" onClick={beginDungeon}>ENTRAR NA FISSURA <span>↗</span></button><small className="dungeon-note">As dungeons alimentam a rota do Novo Deus e abrem regiões mais perigosas.</small></aside>;
  const race = races.find((item) => item.id === profile.raceId)!;
  const playerClass = classes.find((item) => item.id === profile.classId)!;
  const content = menu === "character" ? <><div className="menu-portrait"><CharacterPreview profile={profile} size="small" /></div><h2>{profile.name}</h2><p>{race.name} · {playerClass.name} · {race.talent}</p><div className="detail-stats">{Object.entries(stats).map(([label, value]) => <span key={label}><small>{label}</small><b>{value}</b></span>)}</div><h3>Linhas de evolução</h3><ol>{race.evolution.map((item) => <li key={item}>{item}</li>)}</ol></> : menu === "inventory" ? <><h2>Bolsa de viagem</h2><p>Equipamento e recursos carregados pelo seu eco.</p><div className="item-grid"><span>◈ Núcleo de Essência <b>1</b></span><span>✦ Poção de musgo <b>{potions}</b></span><span>⌁ Madeira viva <b>coletável</b></span><span>◆ Minério de raiz <b>coletável</b></span></div><h3>Equipamento inicial</h3><p><b>{playerClass.weapon}</b> · Manto de viagem · item da origem. Use <b>H</b> para consumir uma poção.</p><h3>Habilidade de classe</h3><p><b>{playerClass.skills[0]}</b> — use <b>R</b> para liberar uma descarga de Éter quando o foco estiver cheio.</p></> : menu === "map" ? <><h2>Mapa de Aetherion</h2><p>O continente responde às escolhas do seu personagem.</p><div className="region-map">{regions.map((region, index) => <span key={region.name} className={region.state}><i>{index + 1}</i><b>{region.name}</b><small>{region.threat}</small></span>)}</div></> : menu === "quests" ? <><h2>Crônicas e escolhas</h2><div className="quest-log"><article><small>PRÓLOGO ATIVO</small><b>O Lobo e a Raiz</b><p>Expulse os Lobos Primordiais da trilha norte e leve a primeira essência à Vila de Musgo.</p></article><article><small>ORIGEM</small><b>{profile.name}</b><p>A origem escolhida vai definir sua primeira aliança e o primeiro título.</p></article><article><small>FINAIS POSSÍVEIS</small><p>{endings.join(" · ")}</p></article></div></> : menu === "codex" ? <><h2>Codex da Grande Ruptura</h2><h3>Dragões Primordiais</h3><div className="codex-row">{primordialDragons.map((dragon) => <span key={dragon}>◉ {dragon}</span>)}</div><h3>Facções</h3><p>Reino Humano · Clãs Monstruosos · Círculo Élfico · Ordem da Vigília · Liga dos Mercadores.</p></> : <><h2>Vila de Musgo</h2><p>Transforme o refúgio em uma civilização. Construções alteram recursos, segurança e missões disponíveis.</p><div className="build-list">{["Cabana", "Horta de musgo", "Forja", "Torre de vigia", "Santuário do Éter"].map((name) => <button key={name} disabled={buildings.includes(name)} onClick={() => build(name)}>{buildings.includes(name) ? "✓ " : "+ "}{name}<small>{name === "Forja" ? "8 minério" : "12 madeira"}</small></button>)}</div></>;
  return <aside className="rpg-menu-window"><button className="menu-close" onClick={close}>×</button><p className="menu-overline">REGISTRO DE AETHERION</p>{content}</aside>;
}

export default function RpgWorldCanvas({ profile, slotId, onReturnToCreation, onLogout }: { profile: CharacterProfile; slotId: string; onReturnToCreation: () => void | Promise<void>; onLogout: () => void | Promise<void> }) {
  const canvasRef = useRef<HTMLCanvasElement>(null); const startingStats = profileStats(profile); const saveKey = `${worldSaveKey}:${slotId}`; const stateRef = useRef<WorldState>(hydrateWorld(profile, startingStats, saveKey));
  const [hud, setHud] = useState<Hud>(() => ({ health: stateRef.current.player.health, maxHealth: stateRef.current.player.maxHealth, focus: 100, maxFocus: 100, level: 1, xp: 0, essence: 0, potions: 2, wolves: 0, notice: stateRef.current.notice, quest: stateRef.current.quest, menu: "none", buildings: ["Cabana"], wood: 20, ore: 8, food: 12, gold: 15, playerX: 20, playerY: 20 }));
  const [menu, setMenu] = useState<Menu>("none");
  const [dialogue, setDialogue] = useState<Npc | null>(null);
  const stats = useMemo(() => profileStats(profile), [profile]); const race = races.find((item) => item.id === profile.raceId)!;

  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return; const ctx = canvas.getContext("2d", { alpha: false }); if (!ctx) return; const keys = new Set<string>(); const combatTexts: CombatText[] = []; let audio: AudioContext | null = null; let frame = 0; let previous = performance.now(); let uiTimer = 0; let saveTimer = 0; let raf = 0; const logicalWidth = 960; const logicalHeight = 540;
    const resize = () => { canvas.width = logicalWidth; canvas.height = logicalHeight; ctx.imageSmoothingEnabled = false; ctx.setTransform(1, 0, 0, 1, 0, 0); };
    const spawnCombatText = (x: number, y: number, text: string, color: string, scale = 1) => combatTexts.push({ id: `${performance.now()}-${Math.random()}`, x, y, text, color, life: .72, maxLife: .72, scale });
    const playCombatSound = (kind: "hit" | "block" | "defeat" | "hurt" | "ether") => { try { audio ??= new AudioContext(); if (audio.state === "suspended") void audio.resume(); const now = audio.currentTime; const oscillator = audio.createOscillator(); const gain = audio.createGain(); const spec = kind === "hit" ? { wave: "square" as OscillatorType, from: 160, to: 78, duration: .09, volume: .055 } : kind === "block" ? { wave: "triangle" as OscillatorType, from: 480, to: 310, duration: .11, volume: .045 } : kind === "defeat" ? { wave: "sawtooth" as OscillatorType, from: 260, to: 48, duration: .25, volume: .065 } : kind === "hurt" ? { wave: "square" as OscillatorType, from: 95, to: 54, duration: .12, volume: .06 } : { wave: "sine" as OscillatorType, from: 360, to: 720, duration: .19, volume: .045 }; oscillator.type = spec.wave; oscillator.frequency.setValueAtTime(spec.from, now); oscillator.frequency.exponentialRampToValueAtTime(spec.to, now + spec.duration); gain.gain.setValueAtTime(spec.volume, now); gain.gain.exponentialRampToValueAtTime(.001, now + spec.duration); oscillator.connect(gain).connect(audio.destination); oscillator.start(now); oscillator.stop(now + spec.duration); } catch { /* áudio é opcional quando o navegador o bloqueia */ } };
    const keydown = (event: KeyboardEvent) => { if (["Space", "ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"].includes(event.code)) event.preventDefault(); keys.add(event.code); if (event.repeat) return; const world = stateRef.current; const player = world.player;
      const beginDeath = (enemy: Enemy, reward: number) => { enemy.health = 0; enemy.hurt = .22; enemy.death = .6; world.player.xp += reward; spawnCombatText(enemy.x, enemy.y - .7, `+${reward} XP`, "#e7bd58", 1.12); playCombatSound("defeat"); world.notice = `${enemy.kind === "wolf" ? "Lobo Primordial" : "Criatura"} perde a forma e se dissipa em Éter.`; };
      if (event.code === "Space" && player.attack <= 0) { player.attack = .33; const targets = world.enemies.filter((enemy) => enemy.alive && !enemy.death && distance(player, enemy) < 1.45); if (!targets.length) world.notice = "A lâmina encontrou apenas névoa. Aproxime-se da criatura."; targets.forEach((enemy) => { const guarded = enemy.kind === "goblin" && Math.sin(enemy.phase * 2.4) > .35; const damage = guarded ? 1 : 1 + (stats.power >= 9 ? 1 : 0); enemy.guard = guarded ? .25 : 0; enemy.health -= damage; enemy.hurt = .18; spawnCombatText(enemy.x, enemy.y - .55, guarded ? `BLOQUEIO ${damage}` : `-${damage}`, guarded ? "#8bd5c0" : "#f2d18a", guarded ? .78 : 1); playCombatSound(guarded ? "block" : "hit"); if (guarded) world.notice = "A criatura se protegeu, reduzindo o impacto."; if (enemy.health <= 0) beginDeath(enemy, 12); }); }
      if (event.code === "KeyF") { const essence = world.essences.find((item) => distance(player, item) < 1.1); const node = gatherNodes.find((item) => !world.gathered.has(item.id) && distance(player, item) < 1.1); if (essence) { world.essences = world.essences.filter((item) => item.id !== essence.id); player.essence += 1; if (player.essence >= 3 && !player.evolved) { player.evolved = true; world.notice = `Evolução iniciada: ${race.evolution[0]} desperta dentro de você.`; } else world.notice = "A essência se mistura à sua forma."; } else if (node) { world.gathered.add(node.id); world.resources[node.kind] += 4; world.notice = node.kind === "wood" ? "Madeira viva coletada para a Vila de Musgo." : "Minério de raiz coletado. A forja pode usar isso."; } else world.notice = "Nenhuma essência ou recurso está ao alcance."; }
      if (event.code === "KeyH") { if (player.potions > 0 && player.health < player.maxHealth) { player.potions -= 1; player.health = Math.min(player.maxHealth, player.health + 28 + stats.resolve * 2); world.notice = "A poção de musgo recompõe sua forma."; } else world.notice = player.potions ? "Sua vitalidade já está plena." : "A bolsa não guarda mais poções."; }
      if (event.code === "KeyR" && player.special <= 0) { if (player.focus < 35) world.notice = "O foco de Éter ainda não responde."; else { player.focus -= 35; player.special = .62; playCombatSound("ether"); const classInfo = classes.find((item) => item.id === profile.classId)!; const targets = world.enemies.filter((enemy) => enemy.alive && !enemy.death && distance(player, enemy) < 2.7); targets.forEach((enemy) => { const damage = 1 + Math.floor(stats.ether / 4); enemy.health -= damage; enemy.hurt = .25; spawnCombatText(enemy.x, enemy.y - .7, `-${damage}`, "#8ff3d0", 1.18); if (enemy.health <= 0) beginDeath(enemy, 15); }); world.notice = `${classInfo.skills[0]} rasga a clareira e alcança ${targets.length || "nenhuma"} criatura.`; } }
      if (event.code === "KeyE") { const npc = Npcs.find((item) => distance(player, item) < 1.45); if (distance(player, { x: 20.2, y: 4.8 }) < 1.45) setMenu("dungeon"); else if (npc) setDialogue(npc); else world.notice = "Nada aqui responde ao seu chamado."; }
      const menuByKey: Record<string, Menu> = { KeyC: "character", KeyI: "inventory", KeyM: "map", KeyQ: "quests", KeyB: "village", KeyJ: "codex" }; if (menuByKey[event.code]) setMenu((old) => old === menuByKey[event.code] ? "none" : menuByKey[event.code]);
    };
    const keyup = (event: KeyboardEvent) => keys.delete(event.code); window.addEventListener("resize", resize); window.addEventListener("keydown", keydown); window.addEventListener("keyup", keyup); resize();
    const emit = () => { const world = stateRef.current; const defeated = world.enemies.filter((enemy) => enemy.kind === "wolf" && !enemy.alive).length; setHud((old) => ({ ...old, health: Math.ceil(world.player.health), maxHealth: world.player.maxHealth, focus: world.player.focus, maxFocus: world.player.maxFocus, level: world.player.level, xp: world.player.xp, essence: world.player.essence, potions: world.player.potions, wolves: defeated, notice: world.notice, quest: defeated >= 3 ? "Leve a essência à Vila de Musgo" : "Expulse os Lobos Primordiais da trilha norte", buildings: [...world.buildings], wood: world.resources.wood, ore: world.resources.ore, food: world.resources.food, gold: world.resources.gold, playerX: world.player.x, playerY: world.player.y })); };
    const loop = (now: number) => { const delta = Math.min(.05, (now - previous) / 1000); previous = now; frame += delta; const world = stateRef.current; const p = world.player; let mx = 0; let my = 0; if (keys.has("KeyW") || keys.has("ArrowUp")) my -= 1; if (keys.has("KeyS") || keys.has("ArrowDown")) my += 1; if (keys.has("KeyA") || keys.has("ArrowLeft")) mx -= 1; if (keys.has("KeyD") || keys.has("ArrowRight")) mx += 1; if (mx || my) { const len = Math.hypot(mx, my); mx /= len; my /= len; const speed = 3 + stats.agility * .06; const nx = clamp(p.x + mx * speed * delta, 1, WORLD_W - 2); const ny = clamp(p.y + my * speed * delta, 1, WORLD_H - 2); if (!isTree(Math.round(nx), Math.round(ny)) && terrain(Math.round(nx), Math.round(ny)) !== "water") { p.x = nx; p.y = ny; p.facing = mx || p.facing; } }
      p.attack = Math.max(0, p.attack - delta); p.invulnerable = Math.max(0, p.invulnerable - delta); for (let index = combatTexts.length - 1; index >= 0; index -= 1) { combatTexts[index].life -= delta; combatTexts[index].y -= delta * .82; if (combatTexts[index].life <= 0) combatTexts.splice(index, 1); } for (const enemy of world.enemies) if (enemy.alive) { enemy.phase += delta; enemy.hurt = Math.max(0, enemy.hurt - delta); enemy.attack = Math.max(0, (enemy.attack ?? 0) - delta); enemy.guard = Math.max(0, (enemy.guard ?? 0) - delta); if ((enemy.death ?? 0) > 0) { enemy.death = Math.max(0, (enemy.death ?? 0) - delta); if (!enemy.death) { enemy.alive = false; world.essences.push({ id: `essence-${enemy.id}`, x: enemy.x, y: enemy.y, phase: 0 }); } continue; } const d = distance(enemy, p); if (d < 4.5 && d > .78) { enemy.x += ((p.x - enemy.x) / d) * delta * .38; enemy.y += ((p.y - enemy.y) / d) * delta * .38; } if (d < .85 && p.invulnerable <= 0) { enemy.attack = .35; p.health -= 5; p.invulnerable = .7; spawnCombatText(p.x, p.y - .75, "-5", "#f07d72", 1.05); playCombatSound("hurt"); world.notice = "As garras da floresta encontram sua forma. Reposicione-se."; } }
      world.essences.forEach((item) => item.phase += delta * 3); if (p.health <= 0) { p.health = p.maxHealth; p.x = 25; p.y = 21; world.notice = "A Vila de Musgo recompõe seu eco. A floresta ainda espera."; }
      p.focus = Math.min(p.maxFocus, p.focus + delta * (4 + stats.ether * .12)); p.special = Math.max(0, p.special - delta); if (p.xp >= p.level * 40) { p.xp -= p.level * 40; p.level += 1; p.maxHealth += 8; p.health = p.maxHealth; world.notice = `Nível ${p.level}: sua forma se fortaleceu e um novo eco responde.`; } saveTimer += delta; if (saveTimer > 1.5) { saveTimer = 0; persistWorld(profile, world, saveKey); } uiTimer += delta; if (uiTimer > .12) { uiTimer = 0; emit(); }
      const width = logicalWidth; const height = logicalHeight; ctx.clearRect(0, 0, width, height); const tile = 32; const camX = p.x; const camY = p.y; const sx = (x: number) => Math.round((x - camX) * tile + width / 2); const sy = (y: number) => Math.round((y - camY) * tile + height / 2);
      ctx.fillStyle = "#102c27"; ctx.fillRect(0, 0, width, height); const startX = Math.floor(camX - width / tile / 2) - 1; const endX = Math.ceil(camX + width / tile / 2) + 1; const startY = Math.floor(camY - height / tile / 2) - 1; const endY = Math.ceil(camY + height / tile / 2) + 1;
      for (let y = startY; y <= endY; y += 1) for (let x = startX; x <= endX; x += 1) { const t = terrain(x, y); const px = sx(x), py = sy(y); ctx.fillStyle = t === "water" ? "#1b5357" : t === "path" ? "#8b7753" : t === "village" ? "#6b6650" : "#285447"; ctx.fillRect(px, py, tile, tile); if (t === "grass") { ctx.fillStyle = hash(x, y) > .54 ? "#35664d" : "#20463e"; ctx.fillRect(px + 3, py + 5, 3, 7); ctx.fillRect(px + 18, py + 15, 2, 6); ctx.fillStyle = hash(y, x) > .58 ? "#57935a" : "#2c5746"; ctx.fillRect(px + 8 + Math.floor(hash(x + 2, y) * 10), py + 10 + Math.floor(hash(y + 5, x) * 8), 3, 5); if (hash(x, y) > .73) { ctx.fillStyle = "#6fa86a"; ctx.fillRect(px + 22, py + 7, 2, 2); } } if (t === "water") { ctx.fillStyle = "#2f7470"; ctx.fillRect(px + 5, py + 7 + Math.floor(Math.sin(frame + x) * 2), 11, 2); ctx.fillRect(px + 20, py + 19, 7, 2); } if (t === "path") { ctx.fillStyle = "#aa9365"; ctx.fillRect(px + 2, py + 3, tile - 4, 3); ctx.fillStyle = "#715f45"; ctx.fillRect(px + 5, py + 19, tile - 10, 2); } }
      for (let y = startY; y <= endY; y += 1) for (let x = startX; x <= endX; x += 1) if (isTree(x, y)) drawTree(ctx, sx(x + .5), sy(y + .44), 64);
      drawBuilding(ctx, sx(27.1), sy(21.4), 32, "hut"); drawBuilding(ctx, sx(30.2), sy(22.5), 32, "stall"); drawBuilding(ctx, sx(24.8), sy(19.7), 32, "hut"); drawBuilding(ctx, sx(32.2), sy(24.8), 32, "stall"); drawBuilding(ctx, sx(25.8), sy(25.6), 32, "forge"); ctx.fillStyle = "#4c3125"; ctx.fillRect(sx(33.2), sy(20.3), 96, 10); ctx.fillStyle = "#a76b42"; for (let plank = 0; plank < 6; plank += 1) ctx.fillRect(sx(33.2) + plank * 16, sy(20.3) + 2, 3, 7); if (world.buildings.includes("Horta de musgo")) { ctx.fillStyle = "#244e3e"; ctx.fillRect(sx(28.8), sy(24.1), 64, 32); for (let seed = 0; seed < 7; seed += 1) { ctx.fillStyle = seed % 2 ? "#9cca69" : "#5b9e5b"; ctx.fillRect(sx(29) + seed * 8, sy(24.28), 3, 9); } } if (world.buildings.includes("Santuário do Éter")) { ctx.fillStyle = "rgba(90,216,171,.22)"; ctx.fillRect(sx(24.6) - 40, sy(22.9) - 40, 80, 80); ctx.fillStyle = "#e7bd58"; ctx.fillRect(sx(24.6) - 2, sy(22.9) - 24, 4, 48); ctx.fillRect(sx(24.6) - 24, sy(22.9) - 2, 48, 4); ctx.fillStyle = "#77dbb5"; ctx.fillRect(sx(24.6) - 7, sy(22.9) - 7, 14, 14); } ctx.fillStyle = "rgba(116,223,183,.12)"; ctx.fillRect(sx(20.2) - 32, sy(4.8) - 48, 64, 96); ctx.fillStyle = "#e7bd58"; ctx.fillRect(sx(20.2) - 15, sy(4.8) - 32, 4, 64); ctx.fillRect(sx(20.2) + 11, sy(4.8) - 32, 4, 64); ctx.fillStyle = "#6ad8ae"; ctx.fillRect(sx(20.2) - 8, sy(4.8) - 20, 16, 40); ctx.fillStyle = "#b5f1c8"; ctx.fillRect(sx(20.2) - 3, sy(4.8) - 11, 6, 22);
      const ySorted = [ ...Npcs.map((npc) => ({ y: npc.y, render: () => drawPerson(ctx, sx(npc.x), sy(npc.y), 48, npc.race, "#e7bd58", frame + npc.x, 1) })), ...world.enemies.filter((enemy) => enemy.alive).map((enemy) => ({ y: enemy.y, render: () => { const boss = enemy.id === "root-guardian"; if (enemy.death) drawDeath(ctx, sx(enemy.x), sy(enemy.y), enemy.death, boss ? "#e7bd58" : "#79cfa6"); else if (boss) drawBoss(ctx, sx(enemy.x), sy(enemy.y), enemy.phase, enemy.hurt); else drawCreature(ctx, sx(enemy.x), sy(enemy.y), 48, enemy.kind, enemy.phase, enemy.hurt, enemy.attack, enemy.guard); if (!enemy.death) { const hp = enemy.health / enemy.maxHealth; const barWidth = boss ? 56 : 32; const barY = boss ? -60 : -35; ctx.fillStyle = "rgba(7,18,19,.88)"; ctx.fillRect(sx(enemy.x) - barWidth / 2, sy(enemy.y) + barY, barWidth, 5); ctx.fillStyle = "#d85f59"; ctx.fillRect(sx(enemy.x) - barWidth / 2 + 1, sy(enemy.y) + barY + 1, (barWidth - 2) * hp, 3); } } })), { y: p.y, render: () => { drawPerson(ctx, sx(p.x), sy(p.y), 48, profile.raceId, race.palette.accent, frame * 9 * (mx || my ? 1 : .2), p.facing); if (p.attack > 0) { ctx.globalAlpha = p.attack / .33; ctx.fillStyle = race.palette.accent; ctx.fillRect(sx(p.x) + p.facing * 24, sy(p.y) - 18, 32, 5); ctx.fillRect(sx(p.x) + p.facing * 34, sy(p.y) - 8, 22, 5); ctx.fillRect(sx(p.x) + p.facing * 25, sy(p.y) + 4, 28, 5); ctx.globalAlpha = 1; } } } ];
      gatherNodes.filter((node) => !world.gathered.has(node.id)).forEach((node) => { const nx = sx(node.x), ny = sy(node.y); ctx.fillStyle = node.kind === "wood" ? "#4f7d4d" : "#627a91"; ctx.fillRect(nx - 10, ny - 10, 20, 20); ctx.fillStyle = node.kind === "wood" ? "#a8cf70" : "#b6d0d9"; ctx.fillRect(nx - 4, ny - 13, 5, 18); ctx.fillRect(nx - 11, ny - 3, 18, 5); }); world.essences.forEach((essence) => { const ex = sx(essence.x), ey = sy(essence.y) - 13 - Math.sin(essence.phase) * 5; ctx.fillStyle = "rgba(231,189,88,.16)"; ctx.fillRect(ex - 16, ey - 16, 32, 32); ctx.fillStyle = "#e7bd58"; ctx.fillRect(ex - 5, ey - 9, 10, 18); ctx.fillRect(ex - 9, ey - 5, 18, 10); ctx.fillStyle = "#fff2b8"; ctx.fillRect(ex - 3, ey - 3, 6, 6); }); ySorted.sort((a, b) => a.y - b.y).forEach((item) => item.render()); combatTexts.forEach((item) => { const alpha = Math.min(1, item.life / .16); const tx = sx(item.x); const ty = sy(item.y); ctx.save(); ctx.globalAlpha = alpha; ctx.textAlign = "center"; ctx.textBaseline = "middle"; ctx.font = `bold ${Math.round(13 * item.scale)}px monospace`; ctx.fillStyle = "#071719"; ctx.fillText(item.text, tx + 2, ty + 2); ctx.fillStyle = item.color; ctx.fillText(item.text, tx, ty); ctx.restore(); }); if (p.special > 0) drawEtherBurst(ctx, sx(p.x), sy(p.y), p.special, race.palette.accent);
      const nearby = Npcs.find((npc) => distance(p, npc) < 1.5); const nearGate = distance(p, { x: 20.2, y: 4.8 }) < 1.45; if (nearby || nearGate) { const tx = nearby ? sx(nearby.x) : sx(20.2); const ty = nearby ? sy(nearby.y) : sy(4.8); ctx.fillStyle = "rgba(6,21,21,.78)"; ctx.fillRect(tx - 38, ty - 68, 76, 17); ctx.fillStyle = "#e7bd58"; ctx.font = "10px Manrope"; ctx.textAlign = "center"; ctx.fillText(nearGate ? "[E] ENTRAR" : "[E] FALAR", tx, ty - 56); }
      const light = ctx.createRadialGradient(sx(p.x), sy(p.y), 6, sx(p.x), sy(p.y), tile * 3.4); light.addColorStop(0, "rgba(220,255,182,.18)"); light.addColorStop(.55, "rgba(73,172,128,.06)"); light.addColorStop(1, "rgba(3,13,15,.42)"); ctx.fillStyle = light; ctx.fillRect(0, 0, width, height); ctx.strokeStyle = "rgba(177,225,206,.18)"; ctx.lineWidth = 1; for (let particle = 0; particle < 48; particle += 1) { const px = (particle * 71 + frame * 26) % width; const py = (particle * 113 + frame * 44) % height; ctx.beginPath(); ctx.moveTo(px, py); ctx.lineTo(px - 2, py + 7); ctx.stroke(); } const vignette = ctx.createRadialGradient(width / 2, height / 2, Math.min(width, height) * .26, width / 2, height / 2, Math.max(width, height) * .8); vignette.addColorStop(0, "transparent"); vignette.addColorStop(1, "rgba(3,13,15,.68)"); ctx.fillStyle = vignette; ctx.fillRect(0, 0, width, height); raf = requestAnimationFrame(loop); };
    raf = requestAnimationFrame(loop); return () => { persistWorld(profile, stateRef.current, saveKey); cancelAnimationFrame(raf); window.removeEventListener("resize", resize); window.removeEventListener("keydown", keydown); window.removeEventListener("keyup", keyup); };
    }, [profile, race.palette.accent, race.evolution, race.talent, stats.agility, stats.power, stats.ether, stats.resolve]);
  const build = (name: string) => { const world = stateRef.current; const plans: Record<string, { wood: number; ore: number; food: number; effect: string }> = { "Cabana": { wood: 12, ore: 0, food: 0, effect: "Novos viajantes encontram abrigo." }, "Horta de musgo": { wood: 10, ore: 0, food: 0, effect: "A horta passa a produzir alimento para a vila." }, "Forja": { wood: 12, ore: 8, food: 0, effect: "A forja melhora o equipamento das expedições." }, "Torre de vigia": { wood: 15, ore: 2, food: 0, effect: "A torre revela ameaças próximas no mapa." }, "Santuário do Éter": { wood: 8, ore: 4, food: 0, effect: "O santuário estabiliza a evolução e o foco." } }; const plan = plans[name]; if (world.resources.wood < plan.wood || world.resources.ore < plan.ore || world.resources.food < plan.food) { world.notice = "Recursos insuficientes. Colete madeira, minério ou alimento antes de construir."; return; } world.resources.wood -= plan.wood; world.resources.ore -= plan.ore; world.resources.food -= plan.food; if (name === "Horta de musgo") world.resources.food += 8; if (name === "Santuário do Éter") { world.player.focus = world.player.maxFocus; world.player.essence += 1; } if (name === "Forja") world.player.potions += 1; world.buildings.push(name); world.notice = `${name} erguido. ${plan.effect}`; };
  const beginDungeon = () => { const world = stateRef.current; if (world.enemies.some((enemy) => enemy.id === "root-guardian" && enemy.alive)) { world.notice = "O Guardião da Raiz já espera por você na clareira."; setMenu("none"); return; } world.enemies.push({ id: "root-guardian", x: 21.4, y: 6.2, health: 12, maxHealth: 12, kind: "wolf", alive: true, hurt: 0, phase: 0 }); world.quest = "Derrote o Guardião da Raiz e recupere o Fragmento Primordial"; world.notice = "O Guardião da Raiz desperta. Sua história entrou na primeira dungeon."; setMenu("none"); };
  const world = stateRef.current;
  const leaveCharacter = () => { persistWorld(profile, stateRef.current, saveKey); void onReturnToCreation(); };
  const logoutCharacter = () => { persistWorld(profile, stateRef.current, saveKey); void onLogout(); };
  const chooseDialogue = (choice: { label: string; effect: string; faction: string; amount: number }) => { world.reputation[choice.faction] = (world.reputation[choice.faction] ?? 0) + choice.amount; world.notice = `${choice.effect} Reputação com ${choice.faction}: ${world.reputation[choice.faction] > 0 ? "+" : ""}${world.reputation[choice.faction]}.`; setDialogue(null); };
  const touchKey = (code: string, down: boolean) => window.dispatchEvent(new KeyboardEvent(down ? "keydown" : "keyup", { code }));
  return <main className="rpg-shell"><canvas ref={canvasRef} className="rpg-canvas" aria-label="Mapa 2D explorável da Floresta Primordial" />
    <header className="rpg-topbar"><div className="world-brand"><span>✦</span><div><small>ECOS DE AETHERION</small><b>FLORESTA PRIMORDIAL</b></div></div><div className="world-resources"><span>⌁ {hud.wood}</span><span>◆ {hud.ore}</span><span>◒ {hud.food}</span><span>¤ {hud.gold}</span></div><div className="topbar-actions"><button onClick={leaveCharacter} title="Voltar à seleção de personagens">TROCAR ECO</button><button className="logout-button" onClick={logoutCharacter}>SAIR</button></div></header>
    <section className="player-hud"><div className="hud-name"><small>NÍVEL {hud.level}</small><b>{profile.name}</b><span>{race.name} · {classes.find((item) => item.id === profile.classId)?.name}</span></div><div className="life-bar"><i style={{ width: `${hud.health / hud.maxHealth * 100}%` }} /></div><div className="focus-bar"><i style={{ width: `${hud.focus / hud.maxFocus * 100}%` }} /></div><div className="hud-numbers"><span>VIDA {hud.health}/{hud.maxHealth}</span><span>FOCO {Math.ceil(hud.focus)}</span><span>ESSÊNCIA {hud.essence}</span></div></section>
    <section className="quest-hud"><small>MISSÃO ATIVA</small><b>{hud.quest}</b><p>{hud.wolves}/3 Lobos Primordiais dissipados · {hud.notice}</p></section>
    <aside className="minimap" aria-label="Minimapa da Floresta Primordial"><small>MINIMAPA</small><div className="minimap-land"><i className="map-water water-a" /><i className="map-water water-b" /><i className="map-village" /><i className="map-dungeon" />{Npcs.map((npc) => <i key={npc.id} className="map-npc" style={{ left: `${npc.x / WORLD_W * 100}%`, top: `${npc.y / WORLD_H * 100}%` }} />)}{world.enemies.filter((enemy) => enemy.alive).map((enemy) => <i key={enemy.id} className="map-enemy" style={{ left: `${enemy.x / WORLD_W * 100}%`, top: `${enemy.y / WORLD_H * 100}%` }} />)}<i className="map-player" style={{ left: `${hud.playerX / WORLD_W * 100}%`, top: `${hud.playerY / WORLD_H * 100}%` }} /></div></aside>
    <nav className="rpg-actions" aria-label="Menus do RPG"><button onClick={() => setMenu("character")}><kbd>C</kbd><span>Eco</span></button><button onClick={() => setMenu("inventory")}><kbd>I</kbd><span>Bolsa</span></button><button onClick={() => setMenu("map")}><kbd>M</kbd><span>Mapa</span></button><button onClick={() => setMenu("quests")}><kbd>Q</kbd><span>Crônicas</span></button><button onClick={() => setMenu("village")}><kbd>B</kbd><span>Vila</span></button><button onClick={() => setMenu("codex")}><kbd>J</kbd><span>Codex</span></button></nav>
    <div className="touch-controls" aria-label="Controles por toque"><div className="touch-dpad"><button onPointerDown={() => touchKey("KeyW", true)} onPointerUp={() => touchKey("KeyW", false)} onPointerLeave={() => touchKey("KeyW", false)}>▲</button><button onPointerDown={() => touchKey("KeyA", true)} onPointerUp={() => touchKey("KeyA", false)} onPointerLeave={() => touchKey("KeyA", false)}>◀</button><button onPointerDown={() => touchKey("KeyS", true)} onPointerUp={() => touchKey("KeyS", false)} onPointerLeave={() => touchKey("KeyS", false)}>▼</button><button onPointerDown={() => touchKey("KeyD", true)} onPointerUp={() => touchKey("KeyD", false)} onPointerLeave={() => touchKey("KeyD", false)}>▶</button></div><div className="touch-actions"><button onPointerDown={() => touchKey("Space", true)} onPointerUp={() => touchKey("Space", false)}>ATQ</button><button onPointerDown={() => touchKey("KeyR", true)} onPointerUp={() => touchKey("KeyR", false)}>ÉTER</button><button onPointerDown={() => touchKey("KeyF", true)} onPointerUp={() => touchKey("KeyF", false)}>ABS</button><button onPointerDown={() => touchKey("KeyE", true)} onPointerUp={() => touchKey("KeyE", false)}>FALAR</button></div></div>
    <footer className="world-controls"><span><kbd>WASD</kbd> mover</span><span><kbd>ESPAÇO</kbd> atacar</span><span><kbd>R</kbd> técnica</span><span><kbd>F</kbd> absorver/coletar</span><span><kbd>H</kbd> curar</span><span><kbd>E</kbd> conversar</span></footer>
    <MenuWindow menu={menu} close={() => setMenu("none")} profile={profile} stats={stats} buildings={hud.buildings} potions={hud.potions} build={build} beginDungeon={beginDungeon} />
    {dialogue && <div className="dialogue-box"><button onClick={() => setDialogue(null)}>×</button><small>{dialogue.role.toUpperCase()}</small><h2>{dialogue.name}</h2><p>“{dialogue.line}”</p><div><b>NOVO VÍNCULO</b><span>{dialogue.quest}</span></div><section className="dialogue-choices">{dialogueChoices[dialogue.id].map((choice) => <button key={choice.label} onClick={() => chooseDialogue(choice)}><b>{choice.label}</b><span>{choice.effect}</span></button>)}</section><em>Escolhas mudam sua reputação e rotas de missão.</em></div>}
  </main>;
}
